SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'STG') EXEC('CREATE SCHEMA STG');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'RV') EXEC('CREATE SCHEMA RV');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'BV') EXEC('CREATE SCHEMA BV');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'IM') EXEC('CREATE SCHEMA IM');
